server:
  port: ${PORT:9999}

spring:
  application:
    name: twdAPIGateway
  
zuul:
  ignored-services: '*'
  routes:
    TWDLOGIN: /login/**
    TWDMAIN: /main/**
    TWDFREEBILL: /freebill/**    
    
eureka:  
  instance:    
    prefer-ip-address: true    
    ip-address: ${CF_INSTANCE_IP}    
    non-secure-port: ${CF_INSTANCE_PORT}
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}    
    lease-renewal-interval-in-seconds: 15  
  client:    
    region: default    
    fetch-registry: true    
    registry-fetch-interval-seconds: 30    
    register-with-eureka: true    
    service-url:      
     defaultZone: ${vcap.services.DiscoveryService-i5.credentials.uri}/eureka/